[package]
name = "maze-defence-rendering-macroquad"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow.workspace = true
glam = "0.24"
macroquad = { version = "0.3", default-features = false }
maze-defence-rendering = { path = "../rendering" }
