[package]
name = "maze-defence-rendering-macroquad"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow.workspace = true
macroquad = "0.3"
maze-defence-rendering = { path = "../rendering" }
