[package]
name = "maze-defence-system-spawning"
version = "0.1.0"
edition.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
maze-defence-core = { path = "../../core" }

[dev-dependencies]
maze-defence-world = { path = "../../world" }
