[package]
name = "maze-defence-world"
version = "0.1.0"
edition.workspace = true

[lib]
path = "src/lib.rs"

[features]
tower_scaffolding = []

[dependencies]
maze-defence-core = { path = "../core" }
