[package]
name = "maze-defence-system-wave-generation"
version = "0.1.0"
edition.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
maze-defence-core = { path = "../../core" }
sha2 = "0.10"

[dev-dependencies]
maze-defence-core = { path = "../../core" }
